<?php

use App\Services\HelpReferenceService;

/**
 * llms.txt is only useful if something can find it. A `<link rel="llms-txt">`
 * in the document head is a declaration, not a link a crawler follows, and
 * llms.txt is a convention rather than a ratified standard - so nothing indexes
 * the file on its own. The chain that makes it discoverable is:
 *
 *   sitemap.xml -> /help/reference (server-rendered HTML, the only crawlable
 *   docs surface on the site) -> body copy + /help/reference/for-machines/llms-txt
 *   -> /llms.txt -> back to the explainer page.
 *
 * Every link in that chain is asserted below. Breaking one silently undoes the
 * whole thing, which is exactly what happened before these pages existed.
 */
it('ships llms.txt and its explainer page', function () {
    expect(file_exists(public_path('llms.txt')))->toBeTrue();

    $entry = app(HelpReferenceService::class)->get('for-machines', 'llms-txt');

    expect($entry)->not->toBeNull()
        ->and($entry['title'])->toBe('llms.txt')
        ->and($entry['body'])->toContain('https://overlabels.com/llms.txt');
});

it('serves the explainer as crawlable html at its own url', function () {
    // Not an Inertia shell: this route renders Blade so the prose is in the
    // response body, which is the entire reason the page lives here and not
    // under /help.
    $response = $this->get('/help/reference/for-machines/llms-txt');

    $response->assertOk();

    expect($response->getContent())
        ->toContain('https://overlabels.com/llms.txt')
        ->toContain('llms.txt - Reference - Overlabels');
});

it('puts body copy about llms.txt on the reference index', function () {
    // The index is the highest-priority page in this section. The link has to be
    // real prose in the article column, not a badge or an icon.
    $html = $this->get('/help/reference')->getContent();

    expect($html)
        ->toContain('href="/llms.txt"')
        ->toContain('/help/reference/for-machines/llms-txt')
        ->toContain('application/ld+json')
        ->toContain('"contentUrl": "https://overlabels.com/llms.txt"');
});

it('anchors llms.txt from the homepage', function () {
    // The homepage is priority 1.0, plain Blade, and the page a crawler reaches
    // first. If the only mention here is <link rel="llms-txt">, there is nothing
    // to follow - that is the whole failure this work exists to fix.
    $html = $this->get('/')->getContent();

    expect($html)
        ->toContain('href="/llms.txt"')
        ->toContain('href="/help/reference/for-machines/llms-txt"')
        ->toContain('Reading this as a machine?');
});

it('links llms.txt from every reference page, not just the index', function () {
    foreach (['/help/reference', '/help/reference/template-tags/channel_followers'] as $url) {
        expect($this->get($url)->getContent())
            ->toContain('href="/llms.txt"')
            ->toContain('rel="llms-txt"');
    }
});

it('links back from llms.txt to the page that explains it', function () {
    // Reciprocal: a crawler that reaches the file should be able to walk back to
    // an HTML page about it.
    expect(file_get_contents(public_path('llms.txt')))
        ->toContain('/help/reference/for-machines/llms-txt');
});

it('lists llms.txt and the for-machines entries in the sitemap', function () {
    $xml = $this->get('/sitemap.xml')->assertOk()->getContent();

    expect($xml)
        ->toContain('<loc>https://overlabels.com/llms.txt</loc>')
        ->toContain('<loc>https://overlabels.com/help/reference/for-machines/llms-txt</loc>')
        ->toContain('<loc>https://overlabels.com/help/reference/for-machines/markdown-endpoints</loc>')
        ->toContain('<loc>https://overlabels.com/help/reference/for-machines/help-reference-index-json</loc>');
});

it('keeps the prebuilt json index in step with the markdown sources', function () {
    // public/help-reference-index.json is generated by `php artisan help:build-index`
    // on post-autoload-dump, and is gitignored. Composer regenerates it in CI, so
    // this guards the local loop: adding a .md file without rerunning the command
    // leaves the fuzzy search - and any machine consuming the JSON - blind to it.
    $path = public_path('help-reference-index.json');

    expect(file_exists($path))->toBeTrue(
        'Run `php artisan help:build-index` - the reference JSON has not been generated.',
    );

    $json = json_decode((string) file_get_contents($path), true);
    $slugs = array_column($json, 'slug');

    expect($slugs)->toContain('llms-txt', 'markdown-endpoints', 'help-reference-index-json')
        ->and(count($json))->toBe(count(app(HelpReferenceService::class)->all()));
});

it('labels the for-machines category the same in php and typescript', function () {
    // useHelpReference.ts holds its own copy for the Alt+R palette. A category
    // missing there renders as a humanised slug ("For Machines" happens to match,
    // but the order array does not fall back to anything sensible).
    $ts = (string) file_get_contents(resource_path('js/composables/useHelpReference.ts'));

    expect(HelpReferenceService::CATEGORY_LABELS['for-machines'])->toBe('For Machines')
        ->and(HelpReferenceService::CATEGORY_ORDER)->toContain('for-machines')
        ->and($ts)->toContain("'for-machines': 'For Machines'")
        ->and($ts)->toContain("'for-machines'];");
});
