name: notify-deploy

on:
  deployment_status:

jobs:
  notify:
    runs-on: ubuntu-latest
    #if: github.event.deployment_status.state == 'success'
    steps:
      - name: Notify clients of new version
        env:
          PUSHER_APP_ID: "2028130"
          PUSHER_APP_KEY: "a29561d1e3433f3eb70c"
          PUSHER_APP_SECRET: ${{ secrets.PUSHER_SECRET }}
        run: |
          TIMESTAMP=$(date -u +%s)
          BODY='{"name":"version.updated","channel":"app-updates","data":"{\"sha\":\"'$GITHUB_SHA'\"}"}'
          MD5=$(echo -n "$BODY" | md5sum | awk '{print $1}')
          STRING_TO_SIGN=$(printf "POST\n/apps/%s/events\nauth_key=%s&auth_timestamp=%s&auth_version=1.0&body_md5=%s" "$PUSHER_APP_ID" "$PUSHER_APP_KEY" "$TIMESTAMP" "$MD5")
          SIGNATURE=$(printf '%s' "$STRING_TO_SIGN" | openssl dgst -sha256 -hmac "$PUSHER_APP_SECRET" | awk '{print $2}')

          curl -s -X POST "https://api-eu.pusher.com/apps/${PUSHER_APP_ID}/events?auth_key=${PUSHER_APP_KEY}&auth_timestamp=${TIMESTAMP}&auth_version=1.0&body_md5=${MD5}&auth_signature=${SIGNATURE}" \
            -H "Content-Type: application/json" \
            -d "$BODY"
